remove duplicates from the list of matched terms per result entry
cherrytwist/Server pull request #558
Opened 2020-11-27 12:51 UTC by techsmyth

2020-11-27 16:08 UTC, valentinyanakiev requested changes
Change forEach with for. It won't be a big performance hit and the risk is not worth it.

2020-11-27 16:08 UTC, valentinyanakiev commented on src/utils/search/search.service.ts
> +  ensureUniqueTermsPerResult(results: ISearchResultEntry[]) {
This might not work if there are many results. array.forEach is parallel in JS and if you assign a value to a variable this might be a problem.

2020-11-27 17:26 UTC, OlegSubik approved these changes

2020-11-30 07:14 UTC, valentinyanakiev approved these changes
:+1:

2020-11-30 07:15 UTC, merged