Make graphql endpoint port configurable
cherrytwist/Server pull request #68
Opened 2020-09-15 05:29 UTC by Bogoev91

### Describe the background of your pull request

Endpoints through which client and server communicate need to be configurable

What does your pull request do? Does it solve a bug (which one?), add a feature?

It makes those endpoints/ports configurable through environment variables

### Additional context

Demo is not yet updated

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE 
     and the contributor license agreement: tba

2020-09-15 05:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cherrytwist/Server?pullRequest=68) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cherrytwist/Server?pullRequest=68) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cherrytwist/Server?pullRequest=68) it.</sub>

2020-09-15 07:40 UTC, atstojanov submitted a review, later dismissed
Include the new environment variable in the README.md

2020-09-15 07:40 UTC, atstoyanov commented on package.json
> +    "start-local":"nodemon -w src --ext ts --exec ts-node -r dotenv/config src/server.ts",
What is the point of start-local? If won't be used for development nodemon is not required. 
Also "start:local" is more suitable name for the scripts. This allow having different purpose of same script. Like (dev, production etc.).

2020-09-15 07:40 UTC, atstoyanov commented on src/server.ts
>    app.listen(
With this solution we rely on having the endpoint set. There should be a default value or configuration validation:
- add default post ( const serverPort = process.env.GRAPHQL_ENDPOINT_PORT || 4000)
- validate configuration (check ConfigurationValidator)

2020-09-15 08:30 UTC, valentinyanakiev requested changes
Some little tweaks required.

2020-09-15 08:30 UTC, valentinyanakiev commented on src/server.ts
>    app.listen(
const ENDPOINT_PORT :)

2020-09-15 08:30 UTC, valentinyanakiev commented on package.json
> +    "start-local":"nodemon -w src --ext ts --exec ts-node -r dotenv/config src/server.ts",
I agree here - remove this and leave it as it is.If we have a default port (see below) configuration for port 4000, this change here won't be necessary

2020-09-16 05:58 UTC, valentinyanakiev approved these changes

2020-09-16 06:06 UTC, valentinyanakiev approved these changes
👍

2020-09-16 06:08 UTC, valentinyanakiev approved these changes
👍

2020-09-16 06:09 UTC, merged