added logic to block renaming to a restricted group name
cherrytwist/Server pull request #751
Opened 2021-01-27 08:58 UTC by techsmyth

2021-01-29 10:09 UTC, valentinyanakiev requested changes
With this logic, the test 'should throw error for updating restricted group name' test/functional/integration/group/groups.it-spec.ts fails so there is a regression where restrictedGroupName can be updated.

2021-01-29 14:30 UTC, Comoque1 commented
Checking the "Search" failing tests

2021-02-01 07:50 UTC, Comoque1 approved these changes

2021-02-01 07:51 UTC, Comoque1 approved these changes

2021-02-01 07:53 UTC, merged