major cleanup of server documentation; docker composition updated
cherrytwist/Server pull request #811
Opened 2021-03-08 19:30 UTC by techsmyth

server documentation split up and revamped:
- multiple sub files
- updated development instructions to use docker composition

reworking of docker composition to 
- isolate from demo
- added simple auth into composition;

2021-03-09 14:03 UTC, valentinyanakiev requested changes
Infinitely better structure. So so so much better and easier to navigate...

Two minor comments - one more technical, one more regarding content:
- try to limit the number of variables and not duplicate them
- you keep telling the story that we have a microservices architecture and it has the same story on the landing page. This is completely untrue - and having the concept of CT Server right next to 'microservices' architecture will be a thorn in the eyes of any technical person and that will be immediately challenged. We have service-oriented architecture but we are worlds apart from the dogmatic microservices approach... Also, these colors are killing me - we really need to land a palette. It's really, _really_ offputting, especially when it's the first thing you see in CT.  Look how easy on the eye are the https://sdgs.un.org/goals colors. Also our own colors in CT are quite good - but the presentations don't reflect that.

2021-03-09 14:03 UTC, valentinyanakiev commented on .env.docker
> +AUTH_SIMPLE_AUTH_CLIENT_SECRET=!#@$#SDFRSF
AUTH_SIMPLE_AUTH_CLIENT_SECRET and SECRET are the same thing

2021-03-09 14:03 UTC, valentinyanakiev commented on docker-compose.yml
> +      - SECRET
SECRET= ...
Don't add an extra env variable in the config which is exactly the same (SECRET <=> AUTH_SIMPLE_AUTH_CLIENT_SECRET) just to pass it directly to the docker-compose.

2021-03-09 14:03 UTC, valentinyanakiev commented on docs/Configuration.md
> +AUTH_AAD_TENANT=[tenant (directory) ID]
placeholder comment -> we need to review this configuration...

2021-03-09 15:07 UTC, techsmyth commented on docs/Configuration.md
> +AUTH_AAD_TENANT=[tenant (directory) ID]
Config needs a wider review

2021-03-09 15:08 UTC, techsmyth commented on docker-compose.yml
> +      - SECRET
Updated...

2021-03-09 15:27 UTC, techsmyth commented on .env.docker
> +AUTH_SIMPLE_AUTH_CLIENT_SECRET=!#@$#SDFRSF
updated

2021-03-10 08:15 UTC, valentinyanakiev approved these changes

2021-03-10 08:16 UTC, merged